### ISSUE TITLE
Output is not JSON?

### ISSUE THREAD

**Issue by evolutionxbox** [brandon93s/html-table-to-json#10]
Despite the name, the output of `HtmlTableToJson` is not a valid JSON string, but is a JS object.

Consider adding this information to the README, as it has confused some users?

https://stackoverflow.com/questions/67210687/convert-invalid-json-to-valid-json-in-javascript

**Comment by brandon93s** [comment]
Most use cases involve transforming or manipulating the resulting extracted data in some manner.  If a JSON *string* representation is needed the output can be passed to `JSON.stringify()` to achieve this.
